package printer

const defaultCopyright = `
   This is autogenerated copyright
   Put your copyright here with "--copyright" argument
`

//const templateCopyright = `
//{{ with $copyright := split "\n" .Copyright }}
//{{ range $cp := $copyright }}
//{{ $cp }} {{ end }}
//{{ end }}
//`

const templateCopyright = ``
